application: vnitresanalyser
version: 3
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "7d"

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /robots\.txt
  static_files: static/robots.txt
  upload: robots\.txt
- url: /static
  static_dir: static
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
